version: "2.2"
services:
  metrics:
    image: test_build    
    network_mode: "host"
    environment:
      MONGO_PWD: ${MONGO_PWD}
      METRICS_USER_TOKEN: ${METRICS_USER_TOKEN}
      METRICS_WS_USER_TOKEN: ${METRICS_WS_USER_TOKEN}
      METRICS_MYSQL_PWD: ${METRICS_MYSQL_PWD}
      SQL_HOST: ${SQL_HOST}
      QUERY_ON: ${QUERY_ON}
      CATALOG_URL: ${CATALOG_URL}
      NARRATIVE_METHOD_STORE: ${NARRATIVE_METHOD_STORE}
      PROFILE_URL: ${PROFILE_URL}
      KB_INTERNAL_USER_URL: ${KB_INTERNAL_USER_URL}
      MONGO_PATH: ${MONGO_PATH}
      METRICSRO_MONGO_PATH: ${METRICSRO_MONGO_PATH}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      WS_URL: ${WS_URL}
      AUTH2_SUFFIX: ${AUTH2_SUFFIX}
      GRP_SUFFIX: ${GRP_SUFFIX}
      WRK_SUFFIX: ${WRK_SUFFIX}
      SHOCK_SUFFIX: ${SHOCK_SUFFIX}
      SERVICE_WIZARD_URL: ${SERVICE_WIZARD_URL}

